version: "3.4"
services:
  postgres:
    restart: always
    image: postgres:12
    environment:
      POSTGRES_USER: db_user
      POSTGRES_PASSWORD: 12345
      POSTGRES_DB: products
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data

  products_app:
    restart: always
    image: theantialex/wwww:latest
    depends_on:
      - postgres
    ports:
      - "80:8081"
    environment:
      PRODUCTS_APP_PG_URL: postgresql://db_user:12345@postgres/products
    extra_hosts:
      - "host.docker.internal:172.17.0.1"
