- name: create directory for products_app
  file:
    path: /etc/docker/compose/products_app
    state: directory
    mode: 0770
    owner: root
    group: docker

- name: deploy docker-compose.yml for products app
  template:
    src: docker-compose.yml.j2
    dest: /etc/docker/compose/products_app/docker-compose.yml
    mode: 0640
    owner: root
    group: docker
  notify:
    - restart products_app

- name: start & enable products service
  service:
    name: docker-compose@products_app
    # Сервис должен запускаться после перезагрузки
    enabled: yes
    # Сервис должен запуститься или быть уже запущен
    state: started

# Требуется для модуля docker_container
# https://docs.ansible.com/ansible/latest/modules/docker_container_module.html#requirements
- name: install python modules
  apt:
    name:
      - python3-docker
    update_cache: yes

# Требуется чтобы все обработчики (handlers) отработали немедленно,
# не дожидаясь обычных точек синхронизации
# https://docs.ansible.com/ansible/latest/modules/meta_module.html#parameters
- name: flush handlers
  meta: flush_handlers

- name: apply database migrations
  docker_container:
    name: db_migrator
    image: "{{ products_app_image }}"
    command: ["products_app-db", "upgrade", "head"]
    networks:
      - name: products_app_default
    auto_remove: yes
    networks_cli_compatible: yes
    env:
      PRODUCTS_APP_PG_URL: postgresql://{{ products_app_pg_user }}:{{ products_app_pg_password }}@postgres/{{ products_app_pg_dbname }}
