"""Initial

Revision ID: e6ba349e5b2f
Revises: 
Create Date: 2022-06-17 21:31:18.361840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6ba349e5b2f'
down_revision = None
branch_labels = None
depends_on = None

ItemType = sa.Enum('OFFER', 'CATEGORY', name='item_type')


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('item_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('type', ItemType, nullable=False),
    sa.Column('price_sum', sa.Integer(), nullable=True),
    sa.Column('price_amount', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk__items'))
    )
    op.create_index(op.f('ix__items__item_id'), 'items', ['item_id'], unique=False)
    op.create_index(op.f('ix__items__parent_id'), 'items', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix__items__parent_id'), table_name='items')
    op.drop_index(op.f('ix__items__item_id'), table_name='items')
    op.drop_table('items')
    # ### end Alembic commands ###
    ItemType.drop(op.get_bind())
